account:
    resource: "@AccountBundle/Controller/"
    type:     annotation
    prefix:   /

categories:
    resource: "@CategoriesBundle/Controller/"
    type:     annotation
    prefix:   /

budget:
    resource: "@BudgetBundle/Controller/"
    type:     annotation
    prefix:   /

# budgetApi:
#     resource: "@BudgetBundle/Controller/Api"
#     type:     annotation
#     prefix:   /api

login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    prefix:   /

transactions:
    resource: "@TransactionsBundle/Controller/"
    type:     annotation
    prefix:   /
